name: release

on:
  push:
    branches:
    - '!*'
    tags:
    - v*.*.*

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3

    - name: "Get short-lived token to access golang repos"
      uses: epidemicsound/github-workflows/.github/actions/github-app-token@main
      id: get_golang_repo_token
      with:
        service-account: "dashboards-go-gha@es-shared-mgmt-02dd.iam.gserviceaccount.com"
        github-app: "golang-r"
        workload-identity-provider: "projects/747834912006/locations/global/workloadIdentityPools/epidemicsound/providers/github"

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: v1.12.3
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/attest-build-provenance@v1
      with:
        subject-path: 'dist/checksums.txt'
